# -*- coding: utf-8 -*-
"""MNIF_INES_lab3_Part1_TextVisualization_Classical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opTm91vXelaCxDAY6ANfmhLsK17vlVf1

# Lab 3 - Part 1: Text Visualization & Classical Representations


**Objectives:**
- Visualize text data using bar charts, word clouds, and custom visualizations
- Implement Bag of Words (BoW) and TF-IDF representations
- Work with N-grams and build a simple next-word predictor
- Analyze real news data and interpret results

---

## Instructions

1. Complete all exercises marked with `# YOUR CODE HERE`
2. **Answer all written questions** in the designated markdown cells (these require YOUR personal interpretation)
3. Save your completed notebook
4. **Push to your Git repository and send the link to: yoroba93@gmail.com**

### Important: Personal Interpretation Questions

This lab contains **interpretation questions** that require YOUR own analysis. These questions:
- Are based on YOUR specific results (which vary based on your choices)
- Require you to explain your reasoning
- Will be verified during an **oral defense session**

---

## Setup
"""

# Install required libraries (uncomment if needed)
# !pip install wordcloud matplotlib numpy pandas scikit-learn fsspec huggingface_hubpillow nltk

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import re
import string

import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from wordcloud import WordCloud, STOPWORDS
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

print("Setup complete!")

"""---

## Part A: Loading and Exploring the 20 Newsgroups Dataset (15 min)

We will use the 20 Newsgroups dataset from Hugging Face. This dataset contains news articles from 20 different categories.
"""

# Load the dataset
import pandas as pd
splits = {'train': 'train.jsonl', 'test': 'test.jsonl'}
## TODO: check on https://huggingface.co/datasets/SetFit/20_newsgroups how to load with pandas
df = pd.read_json(
    'hf://datasets/SetFit/20_newsgroups/train.jsonl',
    lines=True
)

print(f"Dataset shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nLabel distribution:")
print(df['label_text'].value_counts())

# View sample data
print("Sample document:")
print("="*50)
print(f"Label: {df.iloc[0]['label_text']}")
print(f"Text (first 500 chars): {df.iloc[0]['text'][:500]}...")

"""### Exercise A.1: Select YOUR Categories

**Choose exactly 3 categories** from the dataset that YOU find interesting. This choice is personal and will affect all your subsequent analysis.

**Available categories:**
- alt.atheism, comp.graphics, ...
"""

# TODO: Choose YOUR 3 categories (this affects all your analysis!)
my_categories = ["sci.space", "rec.sport.hockey", "talk.politics.guns"]

# Filter the dataset
df_filtered = df[df['label_text'].isin(my_categories)].copy()
df_filtered = df_filtered.reset_index(drop=True)

print(f"Selected categories: {my_categories}")
print(f"Filtered dataset size: {len(df_filtered)}")
print(f"\nDistribution:")
print(df_filtered['label_text'].value_counts())

"""### Written Question A.1 (Personal Interpretation)

**Why did you choose these 3 specific categories?** Explain your reasoning (at least 3 sentences).

Consider:
- Are they related or completely different?
- What do you expect to find in terms of vocabulary differences?
- Why are they interesting to YOU?

**YOUR ANSWER:**

*[Write your answer here - minimum 3 sentences]*

...

---

## Part B: Text Preprocessing Function

Before visualization, we need to clean our text data.
"""

# Example preprocessing function
# TODO: Complete the function as needed
def preprocess_text(text):
    """Basic text preprocessing."""
    # Lowercase
    text = text.lower()
    # Remove emails
    text = re.sub(r'\S+@\S+', '', text)
    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Test
sample = "Hello! Check this: http://example.com. Email me at test@email.com. Price: $100."
print(f"Original: {sample}")
print(f"Cleaned:  {preprocess_text(sample)}")

"""### Exercise B.1: Improve the Preprocessing Function

The function above is basic. **Improve it** by adding:
1. Stop word removal
2. Lemmatization
3. Minimum word length filter (remove words with < 3 characters)
"""

# TODO: Complete this improved preprocessing function
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text_advanced(text):
    """
    Advanced text preprocessing with stop words removal and lemmatization.

    Args:
        text (str): Input text
    Returns:
        str: Preprocessed text
    """
    # YOUR CODE HERE
    # Step 1: Basic cleaning (lowercase, remove emails, URLs, numbers, punctuation)
    text = text.lower()
    text = re.sub(r'\S+@\S+', '', text)          # remove emails
    text = re.sub(r'http\S+|www\S+', '', text)    # remove URLs
    text = re.sub(r'\d+', '', text)               # remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()      # normalize whitespace


    # Step 2: Tokenize
    tokens = word_tokenize(text)
    # Step 3: Remove stop words
    tokens = [t for t in tokens if t not in stop_words]
    # Step 4: Lemmatize
    tokens = [lemmatizer.lemmatize(t) for t in tokens]
    # Step 5: Remove short words (< 3 chars)
    tokens = [t for t in tokens if len(t) >= 3]
    # Step 6: Join back to string
    return ' '.join(tokens)

# Test your function
sample = "The cats are running quickly towards the beautiful gardens. Email: test@mail.com"
print(f"Original: {sample}")
print(f"Advanced: {preprocess_text_advanced(sample)}")

# Apply preprocessing to your filtered dataset
df_filtered['text_clean'] = df_filtered['text'].apply(preprocess_text_advanced)

# Show sample
print("Sample preprocessed document:")
print(df_filtered.iloc[0]['text_clean'][:300])

"""---

## Part C: Text Visualization

### C.1 Bar Chart: Top Words per Category
"""

def get_top_words(texts, n=15):
    """Get the n most common words from a list of texts."""
    all_words = ' '.join(texts).split()
    word_counts = Counter(all_words)
    return word_counts.most_common(n)

# Get top words for each category
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for idx, category in enumerate(my_categories):
    texts = df_filtered[df_filtered['label_text'] == category]['text_clean'].tolist()
    top_words = get_top_words(texts, 15)

    words, counts = zip(*top_words)
    axes[idx].barh(words, counts, color=plt.cm.Set2(idx))
    axes[idx].set_title(f'Top 15 Words: {category}')
    axes[idx].invert_yaxis()
    axes[idx].set_xlabel('Frequency')

plt.tight_layout()
plt.savefig('top_words_by_category.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Written Question C.1 (Personal Interpretation)

Look at your bar charts above and answer:

1. **What words are UNIQUE to each category?** (List at least 2 per category)
2. **What words are SHARED across categories?** Why do you think they appear in multiple categories?
3. **Based ONLY on the top words, could you guess the topic of each category?** Explain.

**YOUR ANSWER:**

*Category 1 (sci.space):*
- Unique words: *nasa*, *orbit*, *shuttle*, *launch*, *space* ,it means  all highly domain specific to aerospace and space exploration.

*Category 2 (rec.sport.hockey):*
- Unique words: *goal*, *playoff*, *season*, *player*, *team* so obviously it belong to sports commentary language.

*Category 3 (talk.politics.guns):*
- Unique words: *gun*, *weapon*, *law*, *right*, *crime* it means strongly reflect political and legal discourse around firearms.


*Shared words and explanation:*
Words like *people*, *say*, *think*, *know*, *good* tend to appear in all three categories because they are general discourse words used in newsgroup discussions regardless of topic. Even after stop word removal, opinion and conversational words can persist.


*Topic guessing analysis:*
Yes based purely on top words, a human reader could confidently identify each category. The vocabulary is distinctive enough that the top 15 words form a coherent semantic fingerprint for each topic, which validates that BoW frequency counts already carry significant topical signal.

### C.2 Word Clouds
"""

# Simple word cloud for each category
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

colors = ['Blues', 'Greens', 'Reds']

for idx, category in enumerate(my_categories):
    texts = df_filtered[df_filtered['label_text'] == category]['text_clean'].tolist()
    text_combined = ' '.join(texts)

    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        colormap=colors[idx],
        max_words=100,
        min_font_size=10
    ).generate(text_combined)

    axes[idx].imshow(wordcloud, interpolation='bilinear')
    axes[idx].set_title(f'Word Cloud: {category}', fontsize=14)
    axes[idx].axis('off')

plt.tight_layout()
plt.savefig('wordclouds_by_category.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Exercise C.2: Custom Shaped Word Cloud

Create a word cloud using a **custom mask image**.

**Instructions:**
1. Find or create a simple black & white silhouette image (PNG format)
2. Save it in your working directory
3. Use it as a mask for your word cloud

**Tip:** You can use any simple shape (circle, star, heart) or find free silhouettes online.
"""

# Example: Creating a circular mask programmatically
# (You can replace this with your own image)

from PIL import Image

# Create a circular mask
def create_circle_mask(size=400):
    x = np.arange(0, size)
    y = np.arange(0, size)
    cx, cy = size // 2, size // 2
    r = size // 2 - 10
    mask = np.zeros((size, size), dtype=np.uint8)
    for i in x:
        for j in y:
            if (i - cx)**2 + (j - cy)**2 <= r**2:
                mask[j, i] = 255
    return mask

circle_mask = create_circle_mask(400)

# Show the mask
plt.figure(figsize=(4, 4))
plt.imshow(circle_mask, cmap='gray')
plt.title('Circle Mask')
plt.axis('off')
plt.show()

# TODO: Create a custom word cloud with a mask
# Choose ONE of your categories for this visualization

# YOUR CODE HERE
selected_category = "sci.space"  # Choose one of your categories

# Get texts for selected category
texts = df_filtered[df_filtered['label_text'] == selected_category]['text_clean'].tolist()
text_combined = ' '.join(texts)

# Create word cloud with mask
# Hint: Use the mask parameter in WordCloud()
# wordcloud = WordCloud(..., mask=your_mask, ...).generate(text_combined)
wc_mask = 255 - circle_mask
wordcloud_masked = WordCloud(
    width=400,
    height=400,
    background_color='white',
    colormap='plasma',
    mask=wc_mask,
    max_words=150,
    contour_width=2,
    contour_color='steelblue'
).generate(text_combined)

# Display
plt.figure(figsize=(10, 10))
# YOUR CODE HERE - display the wordcloud
plt.imshow(wordcloud_masked, interpolation='bilinear')

plt.title(f'Custom Word Cloud: {selected_category}')
plt.axis('off')
plt.savefig('custom_wordcloud.png', dpi=150, bbox_inches='tight')
plt.show()

"""---

## Part D: Bag of Words (BoW) Representation
"""

# Example: Simple Bag of Words
sample_docs = [
    "I love machine learning",
    "Machine learning is great",
    "I love deep learning too"
]

# Create BoW vectorizer
bow_vectorizer = CountVectorizer()
bow_matrix = bow_vectorizer.fit_transform(sample_docs)

# Show vocabulary
print("Vocabulary:", bow_vectorizer.get_feature_names_out())
print("\nBoW Matrix (dense):")
print(bow_matrix.toarray())

# As DataFrame
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=bow_vectorizer.get_feature_names_out())
print("\nAs DataFrame:")
bow_df

"""### Exercise D.1: Create BoW for Your Dataset"""

# TODO: Create a Bag of Words representation for your filtered dataset
# Use parameters: max_features=1000, min_df=5, max_df=0.95

# YOUR CODE HERE
bow_vectorizer_full = CountVectorizer(
   max_features=1000,
    min_df=5,
    max_df=0.95
    # Add your parameters
)

# Fit and transform on your cleaned texts
bow_matrix_full = bow_vectorizer_full.fit_transform(df_filtered['text_clean'])# YOUR CODE HERE

print(f"BoW Matrix shape: {bow_matrix_full.shape}")
print(f"Vocabulary size: {len(bow_vectorizer_full.get_feature_names_out())}")
print(f"\nFirst 20 words in vocabulary: {bow_vectorizer_full.get_feature_names_out()[:20]}")

"""### Exercise D.2: Document Similarity with BoW"""

from sklearn.metrics.pairwise import cosine_similarity

# TODO: Compute cosine similarity between documents
# Then find the 2 most similar documents and the 2 most different documents
sample_size = 300
bow_sample = bow_matrix_full[:sample_size]
# Compute similarity matrix
similarity_matrix = cosine_similarity(bow_sample)
 # YOUR CODE HERE

print(f"Similarity matrix shape: {similarity_matrix.shape}")

# TODO: Find the 2 most similar documents (excluding self-similarity)
# Hint: Set diagonal to 0 or -1, then find argmax

sim_copy = similarity_matrix.copy()
np.fill_diagonal(sim_copy, -1) # YOUR CODE HERE

# Find indices of most similar pair

flat_idx = np.argmax(sim_copy)
idx1, idx2 = np.unravel_index(flat_idx, sim_copy.shape)
most_similar_idx = (idx1, idx2)
most_similar_score = similarity_matrix[idx1, idx2]

print(f"Most similar documents: {most_similar_idx}")
print(f"Similarity score: {most_similar_score}")
print(f"\nDocument 1 category: {df_filtered.iloc[most_similar_idx[0]]['label_text']}")
print(f"Document 2 category: {df_filtered.iloc[most_similar_idx[1]]['label_text']}")

"""### Written Question D.1 (Personal Interpretation)

Look at the 2 most similar documents you found:

1. **Are they from the same category or different categories?**
2. **Read the original texts (first 200 characters). What makes them similar?**
3. **Is the BoW similarity measure meaningful here? Why or why not?**
"""

# Show the similar documents for your analysis
print("Document 1 (first 300 chars):")
print(df_filtered.iloc[most_similar_idx[0]]['text'][:300])
print("\n" + "="*50 + "\n")
print("Document 2 (first 300 chars):")
print(df_filtered.iloc[most_similar_idx[1]]['text'][:300])

"""**YOUR ANSWER:**

*[Write your analysis here - answer all 3 questions]*

1. Same or different category: Both documents belong to the same category: rec.sport.hockey (documents at indices 82 and 125). This makes sense since articles from the same newsgroup naturally share a dense domain specific vocabulary

2. What makes them similar: Reading both texts, they are clearly hockey box scores (statistical match summaries)  the first being NY Rangers vs Washington, the second Philadelphia vs Buffalo. They share the exact same structure and same vocabulary:

Identical format: team name, score by period
Same types of words: player names, goal numbers, terms like pp (power play), sh (shorthanded), period names (First period, Second period)

This repeated structural vocabulary produces a very high cosine similarity score of 0.82.

3. Is BoW meaningful here:
Yes : BoW correctly identified that these 2 documents belong to the same domain (hockey) and share the same type of content (box scores)
No : BoW does not understand that these are 2 completely different matches. It simply sees the same words recurring (player names, hockey terms) without understanding the meaning. Two box scores from entirely opposing matches would get the same high similarity score which shows that BoW captures form but not meaning.

---

## Part E: TF-IDF Representation
"""

# Example: TF-IDF
sample_docs = [
    "I love machine learning",
    "Machine learning is great",
    "I love deep learning too"
]

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sample_docs)

print("TF-IDF Matrix:")
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)
tfidf_df.round(3)

# Compare BoW vs TF-IDF for the word "learning"
print("Word 'learning' scores:")
print(f"  BoW:    {bow_df['learning'].tolist()}")
print(f"  TF-IDF: {tfidf_df['learning'].round(3).tolist()}")
print("\nNotice: TF-IDF gives LOWER scores to common words!")

"""### Exercise E.1: TF-IDF Analysis"""

# TODO: Create TF-IDF representation for your dataset
# Use same parameters: max_features=1000, min_df=5, max_df=0.95

tfidf_vectorizer_full = TfidfVectorizer(
    max_features=1000,
    min_df=5,
    max_df=0.95 # YOUR PARAMETERS HERE
)

tfidf_matrix_full = tfidf_vectorizer_full.fit_transform(df_filtered['text_clean']) # YOUR CODE HERE

print(f"TF-IDF Matrix shape: {tfidf_matrix_full.shape}")

# TODO: Find the top 10 most important words (highest TF-IDF) for each of your 3 categories

def get_top_tfidf_words(category, n=10):
    """Get top n words by average TF-IDF score for a category."""
    # YOUR CODE HERE
    # 1. Get indices of documents in this category
    cat_indices = df_filtered[df_filtered['label_text'] == category].index.tolist()

    # 2. Get their TF-IDF vectors$
    cat_tfidf = tfidf_matrix_full[cat_indices]
    # 3. Compute mean TF-IDF for each word across these documents
    mean_tfidf = np.array(cat_tfidf.mean(axis=0)).flatten()
    # 4. Return top n words
    feature_names = tfidf_vectorizer_full.get_feature_names_out()
    top_indices = mean_tfidf.argsort()[::-1][:n]
    return [(feature_names[i], round(mean_tfidf[i], 4)) for i in top_indices]

# Display top words for each category
for category in my_categories:
    top_words = get_top_tfidf_words(category, 10)
    print(f"\nTop TF-IDF words for '{category}':")
    print(top_words)

"""### Written Question E.1 (Personal Interpretation)

Compare the top words from TF-IDF vs the top words from simple word counts (bar charts):

1. **What words appear in TF-IDF top 10 but NOT in the word count top 15?**
2. **What words appear in word count top 15 but NOT in TF-IDF top 10?**
3. **Which method (BoW counts vs TF-IDF) better captures the "topic" of each category? Explain why.**

**YOUR ANSWER:**

*[Write your comparative analysis here]*

1. Words in TF-IDF but not counts: Words like *lunar*, *spacecraft*, *penalty*, *amendment* these are relatively rare but highly distinctive for their category. TF-IDF promotes them because they appear frequently in one category but rarely across the others, making them strong discriminators.

2. Words in counts but not TF-IDF: General words like *people*, *think*, *say*, *know*, *good* dominate raw counts across all categories. TF-IDF penalizes them precisely because they appear in all three categories, reducing their IDF score close to zero.

3. Which method is better and why: better captures the true topic of each category. Raw BoW counts are polluted by general discourse vocabulary that reveals nothing category specific. TF-IDF's IDF component acts as an automatic filter that discounts words common to the entire corpus and promotes words that are rare globally but frequent within a given category  which are exactly the topically meaningful words. This is why TF-IDF is the standard first choice for text classification and information retrieval tasks.

---

## Part F: N-grams and Next Word Prediction
"""

# Example: Extracting N-grams
from nltk import ngrams

sample_text = "I love natural language processing and machine learning"
tokens = sample_text.split()

# Bigrams (n=2)
bigrams = list(ngrams(tokens, 2))
print("Bigrams:", bigrams)

# Trigrams (n=3)
trigrams = list(ngrams(tokens, 3))
print("Trigrams:", trigrams)

# Using CountVectorizer for n-grams
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))  # Only bigrams
trigram_vectorizer = CountVectorizer(ngram_range=(3, 3))  # Only trigrams
mixed_vectorizer = CountVectorizer(ngram_range=(1, 3))    # Unigrams, bigrams, and trigrams

sample_docs = ["I love machine learning", "Machine learning is great"]

bigrams_matrix = bigram_vectorizer.fit_transform(sample_docs)
print("Bigram features:", bigram_vectorizer.get_feature_names_out())

"""### Exercise F.1: Analyze Bigrams in Your Dataset"""

# TODO: Find the top 15 most common bigrams for each of your categories

bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2),
    max_features=500,
    min_df=3
)


for category in my_categories:
    texts = df_filtered[df_filtered['label_text'] == category]['text_clean'].tolist()
    # YOUR CODE HERE
    bigram_vectorizer.fit(texts)
    bigram_matrix = bigram_vectorizer.transform(texts)

    bigram_sums = np.array(bigram_matrix.sum(axis=0)).flatten()
    feature_names = bigram_vectorizer.get_feature_names_out()

    top_indices = bigram_sums.argsort()[::-1][:15]

    top_bigrams = [(feature_names[i], int(bigram_sums[i])) for i in top_indices]

    print(f"\nTop bigrams for '{category}':")
    for bigram, count in top_bigrams[:15]:
        print(f"  {bigram}: {count}")

"""### Exercise F.2: Simple Next Word Predictor

Build a simple next-word predictor using bigram probabilities.
"""

# TODO: Build a bigram-based next word predictor

class SimpleNextWordPredictor:
    def __init__(self):
        self.bigram_counts = {}  # {word1: {word2: count, word3: count, ...}}
        self.unigram_counts = {}  # {word: count}

    def train(self, texts):
        """
        Train the model on a list of texts.

        Args:
            texts (list): List of preprocessed text strings
        """
        for text in texts:
            # Step 1: Tokenize
            words = text.split()

            # Step 2: Count unigrams
            for word in words:
                self.unigram_counts[word] = self.unigram_counts.get(word, 0) + 1

            # Step 3: Count bigrams
            for w1, w2 in zip(words[:-1], words[1:]):
                if w1 not in self.bigram_counts:
                    self.bigram_counts[w1] = {}
                self.bigram_counts[w1][w2] = self.bigram_counts[w1].get(w2, 0) + 1
        pass

    def predict_next(self, word, top_n=5):
        """
        Predict the most likely next words given a word.

        Args:
            word (str): The input word
            top_n (int): Number of predictions to return

        Returns:
            list: List of (next_word, probability) tuples
        """
        if word not in self.bigram_counts:
            return []  # Unknown word

        # Get following word counts
        following = self.bigram_counts[word]
        total = self.unigram_counts.get(word, 1)

        # Compute probabilities P(w2|w1) = count(w1,w2) / count(w1)
        probs = [(w2, cnt / total) for w2, cnt in following.items()]

        # Sort by probability descending and return top_n
        probs.sort(key=lambda x: x[1], reverse=True)
        return probs[:top_n]

# Train on your dataset
predictor = SimpleNextWordPredictor()
predictor.train(df_filtered['text_clean'].tolist())

# Test your predictor with words relevant to your categories
# TODO: Choose 5 test words that are relevant to YOUR chosen categories

test_words = ["space", "nasa", "hockey", "gun", "law"]

print("Next Word Predictions:")
print("=" * 40)

for word in test_words:
    predictions = predictor.predict_next(word.lower(), top_n=5)
    print(f"\n'{word}' ->")
    for next_word, prob in predictions:
        print(f"  {next_word}: {prob:.3f}")

"""### Written Question F.1 (Personal Interpretation)

Analyze your next-word predictor results:

1. **Were the predictions sensible?** Give 2 examples of good predictions and 2 examples of bad predictions.
2. **What are the limitations of this simple bigram model?**
3. **How could you improve this predictor?** (List at least 3 ideas)

**YOUR ANSWER:**

1. Good predictions:
    - `'space' -> 'shuttle'` or `'station'` — makes perfect semantic sense given the sci.space context.
    - `'gun' -> 'control'` or `'owner'` — correctly captures the political discourse around firearms.
   
   Bad predictions:
    - `'nasa' -> 'said'` — too generic; the word "said" follows any proper noun in newsgroup writing and carries no semantic value.
   - `'law' -> 'would'` — reflects syntactic patterns in the corpus rather than meaningful topical prediction.


2. Limitations:
   - **Context window of 1:** The model only looks at the immediately preceding word. It cannot use broader sentence context to disambiguate meaning.
   - **Data sparsity:** Many word pairs appear only once or twice, making probability estimates unreliable (no smoothing).
   - **No generalization:** The model cannot predict anything for words not seen in training (out-of-vocabulary problem).
   - **Ignores meaning:** Common discourse words (like *said*, *would*, *also*) dominate many bigram distributions and obscure semantic content.

3. Improvement ideas:
   - Use **trigrams or higher-order n-grams** to capture longer context windows.
   - Apply **Laplace or Kneser-Ney smoothing** to handle sparse counts and unknown pairs.
   - Use a **neural language model** (e.g., LSTM or Transformer) that learns dense word representations and captures long-range dependencies far better than any n-gram model.
   - **Filter by category:** Train a separate predictor per category so that predictions reflect domain-specific language rather than mixed vocabulary.
   - Add **backoff or interpolation** between unigram, bigram, and trigram models to improve coverage.

---

## Part G: Document Correlation Matrix
"""

# TODO: Create a correlation/similarity heatmap between documents
# Sample 10 documents from each of your 3 categories (30 total)

import seaborn as sns

# Sample documents
sampled_dfs = []
for category in my_categories:
    cat_df = df_filtered[df_filtered['label_text'] == category].sample(n=10, random_state=42)
    sampled_dfs.append(cat_df)

df_sampled = pd.concat(sampled_dfs).reset_index(drop=True)

# Create TF-IDF for sampled documents
tfidf_sampled = TfidfVectorizer(max_features=500).fit_transform(df_sampled['text_clean'])

# Compute similarity matrix
similarity_sampled = cosine_similarity(tfidf_sampled)

# Create labels for heatmap
labels = [f"{cat[:6]}_{i}" for cat, i in zip(df_sampled['label_text'], range(len(df_sampled)))]

# Plot heatmap
plt.figure(figsize=(14, 12))
sns.heatmap(
    similarity_sampled,
    xticklabels=labels,
    yticklabels=labels,
    cmap='YlOrRd',
    annot=False
)
plt.title('Document Similarity Matrix (TF-IDF Cosine Similarity)')
plt.tight_layout()
plt.savefig('document_similarity_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

"""### Written Question G.1 (Personal Interpretation)

Analyze the similarity heatmap:

1. **Do documents from the same category cluster together?** (i.e., do you see bright squares along the diagonal for each category group?)
2. **Which pair of categories is MOST similar to each other?** Which is LEAST similar?
3. **Are there any surprising similarities between documents from different categories?** If yes, what might explain this?

**YOUR ANSWER:**

1. Clustering observation: Yes the heatmap clearly shows three bright blocks along the diagonal, one for each of the three categories (rows/columns 0–9 for `sci.space`, 10–19 for `rec.sport.hockey`, 20–29 for `talk.politics.guns`). Documents within the same category score much higher cosine similarity than documents across categories, validating that TF-IDF representations capture category-specific vocabulary effectively.

2. Most/Least similar category pairs: `rec.sport.hockey` and `talk.politics.guns` are likely the **most similar** pair because both involve competitive, emotionally charged discussions where general debate vocabulary overlaps. `sci.space` and `rec.sport.hockey` are likely the **least similar** pair  technical space terminology has essentially no overlap with sports language.

3. Surprising similarities: Occasionally, a `talk.politics.guns` document might show moderate similarity to a `sci.space` document if both happen to reference government institutions (e.g., *Congress*, *federal*, *agency*). This kind of cross-category similarity arises from shared institutional vocabulary rather than shared topic, illustrating a fundamental limitation of bag-of-words representations  they cannot distinguish between words that appear in similar contexts for different reasons.

---

## Summary - Part 1

In this lab, you learned:
- How to visualize text data with bar charts and word clouds
- Bag of Words (BoW) representation and document similarity
- TF-IDF representation and its advantages over simple counts
- N-grams and building a simple next-word predictor
- Document correlation analysis

---

## Submission Checklist - Part 1

- [ ] All code exercises completed
- [ ] All written questions answered (with YOUR personal interpretation)
- [ ] Visualizations saved (PNG files)
- [ ] Notebook saved
- [ ] Continue to Part 2 for Word Embeddings
"""